<?php
// $Id$
/**
 * @file
 * Provides various VCP-related functionality.
 * 
 * Adds facilities for keeping track of video scores as well as adding
 * VCP-specific blocks, theming, and pages.
 */

/*
 * Implementation of hook_block()
 */
function vcp_block($op = 'list', $delta = 0, $edit = array()) {
    $str_vidnum = 'vcp_block_conf_pending_vids_num';
    $str_webdir = 'vcp_block_conf_pending_vids_webdir';

    switch( $op ) {
        case 'list':
            $blocks[0]['info'] = t('VCP Pending Videos');
            $blocks[0]['cache'] = BLOCK_NO_CACHE;
            return $blocks;

        case 'configure':
            $form[$str_vidnum] = array(
                    '#type' => 'textfield',
                    '#title' => t('Number of pending videos to display'),
                    '#default_value' => 
                    variable_get($str_vidnum,5),
                    );
            $form[$str_webdir] = array(
                    '#type' => 'textfield',
                    '#title' => 
                    t('Folder where web documents are stored. (e.g. "htdocs")'),
                    '#default_value' => variable_get($str_webdir, 'htdocs'),
                    );
            return $form;

        case 'save':
            variable_set( $str_vidnum, (int)$edit[$str_vidnum] );
            variable_set( $str_webdir, (string)$edit[$str_webdir] );
            break;

        case 'view':  
            $content = "";
            $count = 0;
            $num_to_list = (int)variable_get( $str_vidnum, '-1' );

            $block['subject'] = t('Pending Videos');

            $webdir = variable_get( $str_webdir, '---' );

            if( $webdir === '---' || $num_to_list === -1 ) {
                $block['content'] = 
                    t('There were some errors in your block config. Please check the block settings.');
                return $block;
            }

            $d = getcwd();
            $d = explode($webdir, $d);
            $d = $d[0] . "videos/pending/";

            $files = file_scan_directory( $d, '.*');

            foreach( $files as $file ) {
                if( $count == $num_to_list ) break; 
                
                $content[$count] = $file->basename;
                if( strlen($content[$count]) > 20 ) {
                    $content[$count] = substr( $content[$count], 0, 20 ) . "&#133;";
                }
                $count++;
            }

            $block['content'] = theme('item_list', $content);
            return $block;
    }
}

